//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [Required(ErrorMessage = "Please Put a Unique Name Which Starts With 'P'")]
        [MaxLength(5)]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please Put Your Name")]
        public string Pname { get; set; }
        [Required(ErrorMessage = "Please Put Your Age")]
        public int Age { get; set; }
        [Required(ErrorMessage = "Please Put Your Mobile Number")]
        [MaxLength(11, ErrorMessage = "Give the Valid Number")]
        [MinLength(11, ErrorMessage = "Give the Valid Number")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "Please Put Your Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Put Your Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Give A Password")]
        public string Password { get; set; }
        public string Type { get; set; }

        public virtual Login Login { get; set; }
    }
}
